apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
spec:
  type: NodePort
  selector:
    app: jaeger
  ports:
    - name: jaeger-ui
      protocol: TCP
      port: 16686
      targetPort: 16686
      nodePort: 30002

    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
      nodePort: 30003