---
- name: Check if swap is disabled
  ansible.builtin.import_tasks: tasks/check-swap-disabled.yml

- name: Check if ipv4 forward enabled
  ansible.builtin.import_tasks: tasks/check-ipv4-forward.yml

- name: Check if all of the required packages are installed
  ansible.builtin.import_tasks: tasks/check-installed-packages.yml

- name: Check if kernel modules are successfully loaded
  ansible.builtin.import_tasks: tasks/check-kernel-modules.yml

- name: Check for cmdline params
  ansible.builtin.import_tasks: tasks/check-cmdline-params.yml

- name: Check for containerd config
  ansible.builtin.import_tasks: tasks/check-containerd-config.yml

- name: Check if kubelet and containerd uses the same sandbox image
  ansible.builtin.import_tasks: tasks/compare-kubelet-containerd-sandbox-image.yml

# todo: Automate this
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#verify-mac-address
- name: Display mac addresses of all the nodes. Make sure none of these are equal!
  ansible.builtin.debug:
    msg: "{{ ansible_default_ipv4.macaddress }}"

- name: Get serial number of the board
  ansible.builtin.shell: cat /proc/cpuinfo | grep Serial | cut -d ' ' -f 2
  register: boards_serial_number
  changed_when: false

- name: Display serial numbers of all the nodes. product_uuid is probably this for raspberry pi, right? These should not be same too. 
  ansible.builtin.debug:
    msg: "{{ boards_serial_number.stdout }}"
