apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: portfolio
          image: anilsezer/portfolio:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 443
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
#              value: "Development" # If you open this, replace the DB connectionString too
            - name: TZ
              value: "Europe/Istanbul"
#      imagePullSecrets:
#        - name: dockerlogin
