# Expose the website
apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  selector:
    app: portfolio
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
