apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: anilsezer/portfolio:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 443
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
#              value: "Development" # If you open this, replace the DB connectionString too
            - name: TZ
              value: "Europe/Istanbul"
      imagePullSecrets:
        - name: dockerlogin
