---
  # Essential for Microk8s at Ubuntu: https://ubuntu.com/tutorials/how-to-kubernetes-cluster-on-raspberry-pi#4-installing-microk8s
  # todo: Check if file exists and fail those 2 tasks if it does not exist
  # todo: This condition does not work: when: cmdline_update_result.stdout is search('Nothing to do.')
  # todo: This file need overhaul

  - name: Check if /boot/firmware/cmdline.txt exists
    ansible.builtin.stat:
      path: "/boot/firmware/cmdline.txt"
    register: cmdline_stat
    failed_when: cmdline_stat.stat.exists == false
  
  - name: Check and update cgroup_memory and cgroup_enable in /boot/firmware/cmdline.txt
    ansible.builtin.shell:
      cmd: |
        cmdline_file="/boot/firmware/cmdline.txt"

        # Function to check and update parameter in cmdline.txt
        check_and_update_param() {
            local param_name=$1
            local param_value=$2

            # Check if the parameter already exists in the file
            if grep -q "\<$param_name=$param_value\>" "$cmdline_file"; then
                echo "$param_name=$param_value already exists in $cmdline_file. Nothing to do."
            else
                # Check if the parameter exists with a different value
                if grep -q "\<$param_name=[^ ]\+\>" "$cmdline_file"; then
                    # Replace the existing parameter value with the specified value
                    sed -i "s/\\b\\($param_name=\\)[^ ]\\+/\\1$param_value/g" "$cmdline_file"
                    echo "$param_name updated to $param_value in $cmdline_file."
                else
                    # Add the parameter to the end of the file
                    echo "$param_name=$param_value" >> "$cmdline_file"
                    echo "Added $param_name=$param_value to $cmdline_file."
                fi
            fi
        }

        # Check and update cgroup_memory parameter
        check_and_update_param "cgroup_memory" "1"

        # Check and update cgroup_enable parameter
        check_and_update_param "cgroup_enable" "memory"
    register: cmdline_update_result
  
  - debug:
      msg: "{{ cmdline_update_result.stdout_lines }}"
  
  - name: Reboot a slow machine that might have lots of updates to apply
    ansible.builtin.reboot:
      reboot_timeout: 3600
      msg: "Rebooting machine in 3600 as timeout"
    # when: cmdline_update_result.stdout is search('Nothing to do.')