---
  ### DISABLE SWAP
  - name: Update ubuntu
    ansible.builtin.include_tasks: disable-swap.yml
    
  ### Enable cgroup_enable & cgroup_memory options for Microk8s
  - name: Editing cmdline for supporting MicroK8s
    ansible.builtin.include_tasks: edit-cmdline.yml
  
  # Set some firewall rules. Source: https://ubuntu.com/tutorials/install-a-local-kubernetes-with-microk8s#2-deploying-microk8s
  - name: Allow traffic on cni0 interface
    ansible.builtin.ufw:
      rule: allow
      direction: in
      interface: cni0
    become: yes
    
  - name: Allow outgoing traffic on cni0 interface
    ansible.builtin.ufw:
      rule: allow
      direction: out
      interface: cni0
    become: yes
  
  ### INSTALL MICROK8S
  - name: Install microk8s
    community.general.snap:
      name:
        - microk8s
      classic: true
      channel: "{{ microk8s_version_and_channel }}"
    register: microk8s_install_result
      
  - name: Add user to microk8s group
    ansible.builtin.user:
      name: "{{ ansible_user }}"
      groups: microk8s
      append: yes
    become: yes

  - name: Create ~/.kube directory
    ansible.builtin.file:
      path: "{{ home_path }}/.kube"
      state: directory
      mode: '0700'
    become: yes

# TODO:
#TASK [Reboot a slow machine that might have lots of updates to apply] *******************************************************************************************************************************************************************************
#fatal: [rpi4Red]: FAILED! => {"msg": "The conditional check 'microk8s_install_result.snaps_installed' failed. The error was: error while evaluating conditional (microk8s_install_result.snaps_installed): 'dict object' has no attribute 'snaps_inst
#alled'\n\nThe error appears to be in '/mnt/c/Users/msnan/source/repos/anilsezar/Portfolio/deployment/ansible/foundation/install-microk8s.yml': line 64, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe off
#ending line appears to be:\n\n      msg: \"Rebooting machine in 3600 as timeout\"\n    when: microk8s_install_result.snaps_installed\n    ^ here\n"}
#changed: [rpi5Green]
#changed: [rpi4Blue]
  - name: Reboot a slow machine that might have lots of updates to apply
    ansible.builtin.reboot:
      reboot_timeout: 3600
      msg: "Rebooting machine in 3600 as timeout"
    when: microk8s_install_result.changed