---
- name: Deploy the postgres DB
  become: false
  block:
    - name: Create DB's pod
      ansible.builtin.command: kubectl apply -f ../../db/postgres/postgres-deployment.yml
      changed_when: true

    - name: Create the service required by other apps to access Postgres DB.
      ansible.builtin.command: kubectl apply -f ../../db/postgres/postgres-service.yml
      changed_when: true

- name: Deploy Website
  become: false
  block:
    - name: Create Websites pod
      ansible.builtin.command: kubectl apply -f ../../website/website-razor.yml
      changed_when: true

    - name: Create the service required by others to access website.
      ansible.builtin.command: kubectl apply -f ../../website/website-service.yml
      changed_when: true