apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-ui-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  selector:
    matchLabels:
      app: portfolio-ui
  template:
    metadata:
      labels:
        app: portfolio-ui
    spec:
      containers:
        - name: portfolio-ui
          image: anilsezer/portfolio-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 443 # todo: Remove this
          startupProbe:
            httpGet:
              path: /liveness
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 60
            failureThreshold: 3
# todo: create a grpc connection readiness probe?
#          readinessProbe:
#            httpGet:
#              path: /readiness
#              port: 8080
#            initialDelaySeconds: 60
#            timeoutSeconds: 1
#            periodSeconds: 60
#            failureThreshold: 3
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"

            - name: TZ
              value: "Europe/Istanbul"

            - name: OTEL_COLLECTOR_ENDPOINT
              value: "http://otel-collector-cluster-opentelemetry-collector.default.svc.cluster.local:4317"
            
            - name: GRPC_BASE_URL
              value: "http://portfolio-grpc-service.default.svc.cluster.local:8080"
