apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-nfs-pv
spec:
  capacity:
    storage: 10Gi # Match the size specified in your Helm values
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 192.168.1.122
    path: /grafana
