---
# TODO: UNTESTED CHATGPT CODE
# TODO: test this again in the next Kubernetes version

# INSTALL THIS: ansible-galaxy collection install kubernetes.core

- name: Update CoreDNS ConfigMap
  hosts: kube-master
  tasks:
    - name: Fetch current CoreDNS ConfigMap
      kubernetes.core.k8s_info:
        api_version: v1
        kind: ConfigMap
        namespace: kube-system
        name: coredns
      register: coredns_config

# TODO: Do I need to add node names and ips here? 
# https://coredns.io/plugins/hosts/ this says core-dns checks for /etc/hosts file every 5 seconds
    - name: Update CoreDNS Corefile with hosts plugin
      lineinfile:
        path: /tmp/coredns_config.yaml
        regexp: '^  Corefile: \|'
        insertafter: '^  Corefile: \|'
        line: |
          hosts {
              192.168.1.120 rpi5-green
              192.168.1.121 rpi4-blue
              fallthrough
          }
      when: coredns_config.resources[0].metadata.name == "coredns"

    - name: Apply updated CoreDNS ConfigMap
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/tmp/coredns_config.yaml') }}"

