---
# https://github.com/geerlingguy/raspberry-pi-dramble/blob/master/tasks/cgroup-features.yml
# https://elinux.org/RPiconfig
# Essential for Kubernetes at Ubuntu: https://ubuntu.com/tutorials/how-to-kubernetes-cluster-on-raspberry-pi#4-installing-microk8s
- name: Enable required cgroup features.
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: true
    regexp: '(^.+rootwait(\s+(?!cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1)[\w=/\-\.]+)*)\s*$'
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
    state: present
  register: cgroup_features
  become: true

- name: Get cmdline.txt files default state so we can compare if something goes awry
  when: cgroup_features is changed
  ansible.builtin.import_tasks: ../../generic-tasks/fetch-file.yml
  vars:
    file_path_and_name: /boot/firmware/cmdline.txt
    new_file_path_and_name: "/boot/firmware/cmdline-{{ ansible_hostname }}-default.txt"

- name: Reboot a slow machine that might have lots of updates to apply
  ansible.builtin.reboot:
    reboot_timeout: 3600
    msg: Rebooting machine in 3600 as timeout.
  when: cgroup_features is changed
  become: true

- name: Get cmdline.txt files edited state so we can compare if something goes awry
  when: cgroup_features is changed
  ansible.builtin.import_tasks: ../../generic-tasks/fetch-file.yml
  vars:
    file_path_and_name: /boot/firmware/cmdline.txt
    new_file_path_and_name: /boot/firmware/cmdline-edited.txt
