---
# https://github.com/kubernetes/kubernetes/issues/122577
- name: Get config.toml files previous setting
  ansible.builtin.import_tasks: ../../generic-tasks/extract-sandbox-image-urls.yml

# kubelet uses the most recent image. Use that at containerd.
- name: Replace sandbox_image value with the value from the kubelet flags
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^\s*sandbox_image\s*=\s*".*"'
    line: 'sandbox_image = "{{ sandbox_image_at_kubelet }}"'
    insertafter: '[plugins."io.containerd.grpc.v1.cri"]'
  become: true

- name: Restart the containerd service
  ansible.builtin.systemd:
    name: containerd
    state: restarted
  become: true