---
- name: Apply metallb configs
  ansible.builtin.command: helm repo add jetstack https://charts.jetstack.io --force-update
  become: false

- name: Apply metallb configs
  ansible.builtin.command: >
    helm install \
      cert-manager jetstack/cert-manager \
      --namespace cert-manager \
      --create-namespace \
      --version v1.15.3 \
      --set crds.enabled=true
  become: false
