---
- name: If .kube dir does exists, then do not continue with kubeadm init.
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.kube"
  register: kube_dir_stat

- name: Init with kubeadm
  when: not kube_dir_stat.stat.exists
  block:
    - name: Pull the images for kubeadm.
      ansible.builtin.command: kubeadm config images pull
      become: true
  
    - name: Ensure .kube directory exists in the user's home directory.
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
      become: true
  
    - name: Copy Kubernetes admin.conf to user's .kube/config.
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ ansible_env.HOME }}/.kube/config"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0644'
        remote_src: true
      become: true
  
    - name: Ensure ownership of ~/.kube/config is correct.
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.kube/config"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0644'
      become: true
