# https://github.com/Martlark/pg_dump
services:
  postgres-backup:
    image: anilsezer/pg_dump:arm64
    container_name: postgres-backup
    environment:
      - POSTGRES_DB=postgres
      - COMMAND=dump
      - PGUSER=default-user
      - PGPASSWORD=rgT6%Qk9jTaURwK!&
      - POSTGRES_PASSWORD=rgT6%Qk9jTaURwK!&
      - PGHOST=192.168.1.104
      - PGPORT=30001
      - CRON_SCHEDULE=1 * * * * # Every day at 3am
      - RETAIN_COUNT=4 # Keep this number of backups
    volumes:
      - ./persistent/data:/dump