apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-backup-nfs-pv
spec:
  capacity:
    storage: 90Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.122
    path: /db-backup
