apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-backups-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 90Gi
  volumeName: db-backups-nfs-pv
