apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrent-pv
spec:
  capacity:
    storage: 3.5Ti
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: /mnt/nas/torrent