---
- name: Read the content of /boot/firmware/cmdline.txt
  become: true
  ansible.builtin.command: cat /boot/firmware/cmdline.txt
  register: cmdline_content
  changed_when: false

- name: Output the cmdline contents
  ansible.builtin.debug:
    msg: "{{ cmdline_content.stdout }}"

- name: Does firmware/cmdline file has the right params?
  ansible.builtin.assert:
    that:
      - "'cgroup_enable=memory' in cmdline_content.stdout"
      - "'cgroup_enable=cpuset' in cmdline_content.stdout"
      - "'cgroup_memory=1' in cmdline_content.stdout"

- name: Check if the cmdline stuff is applied
  ansible.builtin.command: cat /proc/cmdline
  register: proc_cmdline
  changed_when: false

- name: Output the proc/cmdline contents
  ansible.builtin.debug:
    msg: "{{ proc_cmdline.stdout }}"

- name: Does proc/cmdline file has the right params?
  ansible.builtin.assert:
    that:
      - "'cgroup_enable=cpuset' in proc_cmdline.stdout"
      - "'cgroup_enable=memory' in proc_cmdline.stdout"
      - "'cgroup_memory=1' in proc_cmdline.stdout"

#- name: Lets do a triple check by using Ansible facts
#  ansible.builtin.assert:
#    that:
#      - "ansible_proc_cmdline.cgroup_enable is defined"
#      - "'cpuset' in ansible_facts.ansible_proc_cmdline.cgroup_enable"
#      - "'memory' in ansible_facts.ansible_proc_cmdline.cgroup_enable"
#      - "ansible_proc_cmdline.cgroup_memory is defined"
#      - "ansible_proc_cmdline.cgroup_memory == '1'"
