---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

# - name: Print the package facts
#   ansible.builtin.debug:
#     var: ansible_facts.packages

- name: Does the required packages are installed?
  ansible.builtin.assert:
    that:
      - "'apt-transport-https' in ansible_facts.packages"
      - "'ca-certificates' in ansible_facts.packages"
      - "'curl' in ansible_facts.packages"
      - "'gnupg' in ansible_facts.packages"
      - "'lsb-release' in ansible_facts.packages"
      - "'nfs-common' in ansible_facts.packages"
      - "'containerd.io' in ansible_facts.packages"
      - "'kubelet' in ansible_facts.packages"
      - "'kubeadm' in ansible_facts.packages"
      - "'kubectl' in ansible_facts.packages"

- name: Check which packages are kept in "hold" state.
  ansible.builtin.command: apt-mark showhold
  changed_when: false
  register: showhold_check
  become: true

- name: Output held packages to the terminal.
  ansible.builtin.debug:
    msg: "Packages that are in 'hold' state: {{ showhold_check.stdout }}"

- name: Verify packages are held
  ansible.builtin.assert:
    that:
      - "'kubelet' in showhold_check.stdout"
      - "'kubectl' in showhold_check.stdout"
      - "'kubeadm' in showhold_check.stdout"