---
- name: Get /etc/containerd/config.toml's metadata.
  ansible.builtin.stat:
    path: /etc/containerd/config.toml
  register: config_toml

- name: Does config.toml file exists?
  ansible.builtin.assert:
    that: config_toml.stat.exists

- name: Read the content of config.toml
  become: true
  ansible.builtin.command: cat /etc/containerd/config.toml
  register: config_toml_content
  changed_when: false

- name: Output the config.toml contents
  ansible.builtin.debug:
    msg: "{{ config_toml_content.stdout }}"

# todo: improve this to be multiline, there can be more than SystemdCgroup. Currently not, but there will be
- name: Extract 'SystemdCgroup' value using regex_search
  set_fact:
    systemd_cgroup_value: "{{ config_toml_content.stdout | regex_search('SystemdCgroup\\s*=\\s*(\\w+)', '\\1') | first }}"

- name: 
  ansible.builtin.debug:
    msg: "{{ systemd_cgroup_value }}"

- name: Does SystemdCgroup is set to true for the runc?
  ansible.builtin.assert:
    that: systemd_cgroup_value == true
    success_msg: "SystemdCgroup is correctly set to true"
    fail_msg: "SystemdCgroup is not set to true in config.toml"

- name: Extract 'cri' from disabled_plugins list
  set_fact:
    cri_present: "{{ config_toml_content.stdout | regex_search('disabled_plugins\\s*=\\s*\\[.*?(cri).*?\\]') }}"

- name: Assert 'cri' is not in the disabled_plugins
  ansible.builtin.assert:
    that: cri_present is defined
    success_msg: "'cri' is not in the disabled_plugins list. Cri is required by Kubernetes, it cannot be disabled."
    fail_msg: "'cri' is found in the disabled_plugins list! Cri is required by Kubernetes, it cannot be disabled."
