---
- name: Read the content of config.toml
  become: true
  ansible.builtin.command: cat /etc/containerd/config.toml
  register: config_toml_content
  changed_when: false

- name: Read the kubeadm flags
  become: true
  ansible.builtin.command: cat /var/lib/kubelet/kubeadm-flags.env
  register: config_toml_content
  changed_when: false

- name: Does SystemdCgroup is set to true for runc?
  ansible.builtin.assert:
    that: systemd_cgroup_value == true
    success_msg: "SystemdCgroup is correctly set to true"
    fail_msg: "SystemdCgroup is not set to true in config.toml"

- name: Extract 'cri' from disabled_plugins list
  set_fact:
    cri_present: "{{ config_toml_content.stdout | regex_search('disabled_plugins\\s*=\\s*\\[.*?(cri).*?\\]') }}"

- name: Assert 'cri' is not in the disabled_plugins
  ansible.builtin.assert:
    that: cri_present is defined
    success_msg: "'cri' is not in the disabled_plugins list. Cri is required by Kubernetes, it cannot be disabled."
    fail_msg: "'cri' is found in the disabled_plugins list! Cri is required by Kubernetes, it cannot be disabled."