---
- name: Get loaded kernel modules list
  ansible.builtin.command: lsmod
  become: false
  register: lsmod_result
  changed_when: false

- name: Output the lsmod result
  ansible.builtin.debug:
    msg: "{{ lsmod_result.stdout }}"

- name: Does kernel module list has br_netfilter and overlay?
  ansible.builtin.assert:
    that:
      - "'br_netfilter' in lsmod_result.stdout"
      - "'overlay' in lsmod_result.stdout"