apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sql-db-secrets
                  key: SQL_DB_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-db-secrets
                  key: SQL_DB_PASSWORD

          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-db-nas
              mountPath: /var/lib/postgresql/data
              readOnly: false
      volumes:
        - name: postgres-db-nas
          nfs:
            server: 192.168.1.122
            path: /db
            readOnly: false