---
- name: Read the contents of config.toml (containerd).
  become: true
  ansible.builtin.command: cat /etc/containerd/config.toml
  register: config_toml_content
  changed_when: false

- name: Extract the sandbox_image value for the containerd config
  ansible.builtin.set_fact:
    sandbox_image_at_containerd: "{{ config_toml_content.stdout | regex_search('sandbox_image\\s*=\\s*[\"]([^\"]+)[\"]', '\\1') | first }}"

- name: Print the sandbox image val for the containerd.
  ansible.builtin.debug:
    msg: "{{ sandbox_image_at_containerd }}"

- name: Read the contents of kubeadm-flags.env (kubelet).
  become: true
  ansible.builtin.command: cat /var/lib/kubelet/kubeadm-flags.env
  register: kubeadm_flags_content
  changed_when: false

- name: Print the kubeadm flags env files contents
  ansible.builtin.debug:
    msg: "{{ kubeadm_flags_content.stdout }}"

- name: Extract the sandbox image(pod-infra-container-image flag) value for the kubelet
  set_fact:
    sandbox_image_at_kubelet: "{{ kubeadm_flags_content.stdout | regex_search('--pod-infra-container-image=([^\"]+)', '\\1') | first }}"

- name: Print the extracted sandbox image info from kubeadm kubelet flags
  ansible.builtin.debug:
    msg: "{{ sandbox_image_at_kubelet }}"
