---
  - name: Check if swap is enabled
    ansible.builtin.shell:
      cmd: "swapon --show"
    register: swap_status
    ignore_errors: true

  - name: Disable swap if it's enabled
    ansible.builtin.command:
      cmd: "sudo sed -i '/ swap / s/^\\(.*\\)$/#\\1/g' /etc/fstab"
    when: swap_status.rc == 0  # If the command to check swap was successful (exit code 0)
