apiVersion: v1
kind: Pod
metadata:
  name: netshoot-debug-pod
spec:
  containers:
    - name: netshoot
      image: nicolaka/netshoot
      restartPolicy: Never
      command:
        - "sleep"
        - "18000" # Keeps the pod running for 5 hours

# kubectl exec -it netshoot-debug-pod -- bash