apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-nfs-pv
spec:
  capacity:
    storage: 8Gi # Match the size specified in your Helm values
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 192.168.1.122
    path: /prometheus
