apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-backup
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/portfolio-db/backup"
