---
  - name: Install Git
    ansible.builtin.package:
      state: present
      name: git
      
  # In Ubuntu/Fedora we have to install it from archive
  # so it's better to check if it's already installed
  - name: Check if dust is already installed on Ubuntu/Fedora
    ansible.builtin.shell: >
      dust --version
    register: dust_rc
    failed_when: false
    changed_when: false

  - name: Install dust on Ubuntu/Fedora
    become: true
    ansible.builtin.unarchive:
      src: "https://github.com/bootandy/dust/releases/download/{{ dustversion }}/dust-{{ dustversion }}-aarch64-unknown-linux-gnu.tar.gz"
      dest: /usr/local/bin
      extra_opts:
        - --strip=1
        - --wildcards
        - '*/dust'
      remote_src: true
    when: dust_rc.rc != 0
    
  - name: Check if eza is already installed
    ansible.builtin.shell: >
      eza --version
    register: eza_rc
    failed_when: false
    changed_when: false
    
  - name: Install Eza
    ansible.builtin.include_tasks: eza.yml
    when: eza_rc.rc != 0

  # fd-find
  - name: Install fd-find
    ansible.builtin.package:
      state: present
      name: fd-find

  - name: Create link fd to fdfind
    ansible.builtin.file:
      src: '/usr/bin/fdfind'
      dest: '/usr/bin/fd'
      state: link

  # bat
  - name: Install bat
    ansible.builtin.package:
      state: present
      name: bat

  - name: Create link bat to batcat in Debian
    ansible.builtin.file:
      src: '/usr/bin/batcat'
      dest: '/usr/bin/bat'
      state: link

  - name: Install zoxide
    ansible.builtin.package:
      state: present
      name: zoxide
      
  # required by the OMZ plugin zsh-interactive-cd
  - name: Install fzf (command-line fuzzy finder)
    ansible.builtin.package:
      state: present
      name: fzf

  - name: Install procs
    community.general.snap:
      name:
        - procs
  
  - name: Install unzip
    ansible.builtin.package:
      state: present
      name: unzip

  - name: Install ripgrep
    ansible.builtin.package:
      state: present
      name: ripgrep