---
# DOES NOT WORK
  
- name: Install zsh
  ansible.builtin.package:
    name: zsh
    state: present

- name: Set user shell to zsh
  ansible.builtin.user:
    name: "{{ my_remote_user }}"
    shell: /bin/zsh