---
#- name: Install Oh My Zsh
#  ansible.builtin.shell:
#    cmd: "curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash -s -- --unattended"
#  become_user: "{{ my_remote_user }}"
  
  - name: Install Oh My Zsh
    ansible.builtin.git:
      repo: https://github.com/ohmyzsh/ohmyzsh.git
      dest: "{{ home_path }}/.oh-my-zsh"
      depth: 1
    become_user: "{{ my_remote_user }}"
  
#  - name: Copy zshrc.zsh-template to .zshrc
#    ansible.builtin.copy:
#      src: "{{ home_path }}/.oh-my-zsh/templates/zshrc.zsh-template"
#      dest: "~/.zshrc"
#    become_user: "{{ my_remote_user }}"
  
  - name: Download zsh-autosuggestions plugin
    ansible.builtin.git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: "{{ home_path }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
      depth: 1
    become_user: "{{ my_remote_user }}"

  - name: Download zsh-completions plugin
    ansible.builtin.git:
      repo: https://github.com/zsh-users/zsh-completions
      dest: "{{ home_path }}/.oh-my-zsh/custom/plugins/zsh-completions"
      depth: 1
    become_user: "{{ my_remote_user }}"

  - name: Download zsh-syntax-highlighting plugin
    ansible.builtin.git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: "{{ home_path }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
      depth: 1
    become_user: "{{ my_remote_user }}"

  - name: Install PowerLevel10K
    ansible.builtin.git:
      repo: https://github.com/romkatv/powerlevel10k.git
      dest: "{{ home_path }}/.oh-my-zsh/custom/themes/powerlevel10k"
      depth: 1
    become_user: "{{ my_remote_user }}"

  - name: Copy zshrc from control node
    ansible.builtin.copy:
      src: ".zshrc"
      dest: "{{ home_path }}/.zshrc"
      mode: 0644
    become_user: "{{ my_remote_user }}"

  - name: Copy p10k.zsh from control node
    ansible.builtin.copy:
      src: ".p10k.zsh"
      dest: "{{ home_path }}/.p10k.zsh"
      mode: 0644
    become_user: "{{ my_remote_user }}"

#      - name: Update .zshrc
#        ansible.builtin.lineinfile:
#          path: "{{ home_path }}/.zshrc"
#          insertafter: EOF
#          line: "source /home/{{ user }}/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme"
