---
- name: Upgrade ubuntu
  ansible.builtin.import_tasks: tasks/upgrade-ubuntu.yml
  
- name: Ensure a directory for apt keyrings exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
    owner: root
    group: root
  become: true
  
- name: Install gpg
  ansible.builtin.apt:
    state: present
    pkg: gpg
    update_cache: true
  become: true

- name: Install some nice tools
  ansible.builtin.import_tasks: tasks/other-tools.yml

# Shell setup
- name: Check if oh-my-zsh is installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: ohmyzsh_installed

- name: Setting oh-my-zsh
  ansible.builtin.import_tasks: "tasks/setup-ohmyzsh.yml"
  when: ansible_env.SHELL != '/bin/zsh' and not ohmyzsh_installed.stat.exists

- name: Upgrade ubuntu
  ansible.builtin.import_tasks: tasks/upgrade-ubuntu.yml
