---
- name: Download GPG key and save it to apt keyrings directory
  ansible.builtin.shell: wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
  args:
    creates: /etc/apt/keyrings/gierens.gpg
  become: true

- name: Add eza repository to sources list
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/gierens.list
    line: deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main
    create: true
  become: true

- name: Set correct permissions for GPG key and sources list
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0644"
  with_items:
    - /etc/apt/keyrings/gierens.gpg
    - /etc/apt/sources.list.d/gierens.list
  become: true

- name: Install eza package
  ansible.builtin.apt:
    name: eza
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true
