---
- name: Update all host/vm packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
  register: package_update_result

- name: Reboot a slow machine that might have lots of updates to apply
  ansible.builtin.reboot:
    reboot_timeout: 3600
    msg: Rebooting machine in 3600 as timeout
  when: package_update_result.changed
  become: true
