---
- name: Update all host/vm packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
  register: package_update_result
  notify:
    - Reboot device

- name: Flush handlers
  meta: flush_handlers
