route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'slack-webhook'
receivers:
  - name: 'slack-webhook'
    slack_configs:
      - api_url: 'PLACEHOLDER'
        channel: '#asd'
        username: 'alertmanager'
        icon_emoji: ':alert:'
        send_resolved: true
        text: |-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Severity:* {{ .Labels.severity }}
            *Status:* {{ .Status }}
            *Starts At:* {{ .StartsAt }}
            *Ends At:* {{ .EndsAt }}
            *Generator URL:* {{ .GeneratorURL }}
          {{ end }}
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']