apiVersion: v1
kind: Service
metadata:
  name: alertmanager-svc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: alertmanager
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
      nodePort: 31389