---
- name: Build & deploy the website to the cluster
  hosts: rpi4red
  gather_facts: true
  become: false
  tasks:
    - name: Start Docker service.
      ansible.builtin.systemd:
        name: docker
        state: started
      become: true

    - name: Get the latest from git.
      ansible.builtin.git:
        repo: https://github.com/anil-sezer/Portfolio
        dest: "{{ ansible_env.HOME }}/Portfolio"
        depth: 1

    - name: Build the websites image.
      ansible.builtin.shell: "cd {{ ansible_env.HOME }}/Portfolio && docker build -f ./Portfolio.WebUi/Dockerfile -t anilsezer/portfolio ."
      register: build_image
      failed_when: build_image.rc != 0
      changed_when: build_image.rc == 0

    - name: Print image build output.
      ansible.builtin.debug:
        msg: "{{ build_image.stdout }}"

    - name: Push the image.
      ansible.builtin.command: docker push anilsezer/portfolio:latest
      register: push_image
      failed_when: push_image.rc != 0
      changed_when: push_image.rc == 0

    - name: Print image push output.
      ansible.builtin.debug:
        msg: "{{ push_image.stdout }}"

    - name: Stop Docker service.
      ansible.builtin.systemd:
        name: docker
        state: stopped
      become: true

    - name: Deploy the website.
      ansible.builtin.command: kubectl rollout restart deployment website-deployment -n default
      delegate_to: localhost
      register: deploy_result

    - name: Print kubectl response.
      ansible.builtin.debug:
        msg: "{{ deploy_result.stdout }}"