# TODO: Debug this, does not work
---
- name: Testing some stuff before adding them to the main flow
  hosts: kubernetes_nodes
  gather_facts: true
  become: true
  handlers:
    - name: Reboot device
      ansible.builtin.reboot:
        reboot_timeout: 3600
        msg: Rebooting machine in 3600 as timeout
      when: package_update_result.changed
      become: true

  tasks:
    - name: Cordon all nodes
      ansible.builtin.command: "k cordon {{ ansible_hostname }}"
      delegate_to: localhost
      
    - name: Drain all nodes
      ansible.builtin.command: "k drain {{ ansible_hostname }} --ignore-daemonsets --delete-emptydir-data"
      delegate_to: localhost
      
      # stop kubelet: sudo systemctl stop kubelet
      # maintenance + restart
      # start kubelet: sudo systemctl start kubelet
      # k uncordon {{ ansible_hostname }}
      
