all:
  hosts:
    rpi5green:
      ansible_host: rpi5-8gb-green.local # 8GB
      ansible_user: anilsezer
    rpi4red:
      ansible_host: rpi4-red-nas.local # 4GB
      ansible_user: anilsezer
    rpi4blue:
      ansible_host: rpi4-blue.local # 8GB
      ansible_user: anilsezer
    rpi3Purple:
      ansible_host: rpi3-purple.local # 1GB # Camera
      ansible_user: pi

control_node:
  hosts:
    rpi5green:

worker_node:
  hosts:
    rpi4blue:
      
nas:
  hosts:
    rpi4red:
