all:
  hosts:
    rpi5green:
      ansible_host: rpi5-8gb-green.local # 8GB
      ansible_user: anilsezer
      ansible_become_pass: replacethisval
    rpi4red:
      ansible_host: rpi4-4gb-red.local # 4GB
      ansible_user: anilsezer
      ansible_become_pass: replacethisval
    rpi4blue:
      ansible_host: rpi4-8gb-blue.local # 8GB
      ansible_user: anilsezer
      ansible_become_pass: replacethisval

control_node:
  hosts:
    rpi5green:

worker_nodes:
  hosts:
    rpi4red:
    rpi4blue:
