---
- name: Update all nodes, then set up some quality-of-life tools, then setup Kubernetes cluster
  hosts: kubernetes_nodes
  gather_facts: true
  # become: true # TODO: Become'ları kaldır, yerine bunu koy
  # TODO: remove manage_etc_hosts from 
  vars_files:
    - variables.yml
  handlers:
    - name: Reboot device
      ansible.builtin.reboot:
        reboot_timeout: 3600
        msg: Rebooting machine in 3600 as timeout
      when: package_update_result.changed
      become: true

  tasks:
    - name: Create local directory for logs
      ansible.builtin.file:
        path: "{{ kubeadm_init_log_dir }}"
        state: directory
      delegate_to: localhost

    - name: Update Ubuntu, then upgrade terminal to oh-my-zsh, then add my terminal config.
      ansible.builtin.import_tasks: os-and-tools/setup-os-and-cli-tools.yml

    - name: Setup Kubernetes!
      ansible.builtin.import_tasks: kubernetes-setup/install-vanilla-kubernetes.yml

# kubectl & kubeadm completion'ı ekle
# kubectl completion -h
# kubeadm completion -h
