---
# Got these from: 
# https://www.lorenzobettini.it/2023/07/my-ansible-role-for-oh-my-zsh-and-other-cli-programs/
# and https://shaunandersonaz.github.io/Ansible-To-Setup-OhMyZSH-and-PowerLevel10K/
- hosts: all
  become: true
  vars:
    dustversion: v1.0.0
    procsversion: v0.14.5
    my_remote_user: anilsezer
    home_path: /home/{{ my_remote_user }}
    microk8s_version_and_channel: 1.30/stable
  tasks:    
    - name: Update ubuntu
      ansible.builtin.include_tasks: foundation/update-ubuntu.yml
      
    - name: Setup fonts
      ansible.builtin.include_tasks: foundation/toolkit/fonts.yml
      
    - name: Install some nice tools
      ansible.builtin.include_tasks: foundation/toolkit/other-tools.yml
      
    - name: Setup Z Shell
      ansible.builtin.include_tasks: foundation/toolkit/setup-zsh.yml

# todo: Somehow oh my zsh is not started when I ssh to it If I install it like this. Check it out.      
    - name: Tasks for setting oh-my-zsh
      ansible.builtin.include_tasks: foundation/toolkit/setup-ohmyzsh.yml
      
    - name: Check if microk8s package is installed
      ansible.builtin.stat:
        path: /var/snap/microk8s/current
      register: microk8s_installed
      
    - name: Install MicroK8s
      ansible.builtin.include_tasks: foundation/microk8s/install-microk8s.yml
      when: not microk8s_installed.stat.exists